class_name GrowthUpgrade02FoodBoost extends Upgrade
## Increases the amount of food generated per second.

var max_level := 5

func _init() -> void:
	level = Main.ref.data.growth_upgrades.u_02_food_boost_level
	title = "Food Generator Efficiency"
	base_cost = 1
	cost = 1
	

func description() -> String:
	var text := "Increase the amount of food generated by the food generator."
	text += "\n[b]Effects: [/b] +1 food / second"
	
	if level < max_level:
		text += "\n[b]Cost: [/b] %s Growth" % cost
	return text

## Virtual class, must be overwritten.
func can_afford() -> bool:
	if level >= max_level:
		return false
	if Main.ref.data.growth >= cost:
		return true
	return false

## Virtual class, must be overwritten.
func level_up() -> void:
	if level >= max_level:
		return
	
	var error : Error = HandlerGrowth.ref.consume_growth(cost)
	
	if error:
		return
	else:
		level += 1
		Main.ref.data.growth_upgrades.u_02_food_boost_level = level
		leveled_up.emit()
		HandlerGrowthUpgrades.ref.upgrade_leveled_up.emit(self)
